version: 2
root-markers:
  - .git/
lint-debounce: 1s
log-level: 1
tools:
  chktex: &chktex
    prefix: chktex
    lint-command: "chktex -q -v0"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c:%n:%m"
    lint-severity: 2

  latexindent: &latexindent
    format-command: "latexindent -"
    format-stdin: true

  raco-fmt: &raco-fmt
    format-command: "raco fmt"
    format-stdin: true

  selene: &selene
    prefix: selene
    lint-ignore-exit-code: true
    lint-command: "selene --color never --quiet -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %trror%m"
      - "%f:%l:%c: %tarning%m"
      - "%f:%l:%c: %tote%m"
    root-markers:
      - "selene.toml"

  shfmt: &shfmt
    format-command: "shfmt"
    format-stdin: true

  vint: &vint
    prefix: vint
    lint-command: "vint -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

languages:
  bash:
    - <<: *shfmt
  lua:
    - <<: *selene
  latex:
    - <<: *latexindent
    - <<: *chktex
  racket:
    - <<: *raco-fmt
  sh:
    - <<: *shfmt
  tex:
    - <<: *latexindent
    - <<: *chktex
  vim:
    - <<: *vint
