highlight GruvboxRedUnderline cterm=underline gui=underline
highlight GruvboxGreenUnderline cterm=underline gui=underline
highlight GruvboxYellowUnderline cterm=underline gui=underline
highlight GruvboxBlueUnderline cterm=underline gui=underline
highlight GruvboxPurpleUnderline cterm=underline gui=underline
highlight GruvboxAquaUnderline cterm=underline gui=underline
highlight GruvboxOrangeUnderline cterm=underline gui=underline
